## Pandas

In [1]:
import pandas as pd

In [48]:
s = pd.Series([10,20,30,40,50,60])
s.name = "Calories"
print(s)

0    10
1    20
2    30
3    40
4    50
5    60
Name: Calories, dtype: int64

In [49]:
s.dtype
s.values

array([10, 20, 30, 40, 50, 60])

In [50]:
s.index

RangeIndex(start=0, stop=6, step=1)

In [51]:
s[0:3]

0    10
1    20
2    30
Name: Calories, dtype: int64

In [52]:
#iloc -> location based indexing
s.iloc[3]

np.int64(40)

In [53]:
s.iloc[0:3]

0    10
1    20
2    30
Name: Calories, dtype: int64

In [54]:
index = ["apple", "banana", "orange", "grapes", "mango", "kiwi"]
s.index = index
print(s)
print(s["grapes"])

apple     10
banana    20
orange    30
grapes    40
mango     50
kiwi      60
Name: Calories, dtype: int64
40

In [55]:
#loc -> label based indexing
print(s.loc[["grapes", "mango"]])
#In the label based indexing your start as well as end index is included in the output.
s.loc["banana":"grapes"]

grapes    40
mango     50
Name: Calories, dtype: int64

banana    20
orange    30
grapes    40
Name: Calories, dtype: int64

In [56]:
fruit_protin = {
    "apple": 5.3,
    "banana": 1.3,
    "orange": 0.9,
    "grapes": 2.6,
    "mango": 0.8,
    "kiwi": 1.1,
    "avacado": 2.0
}
s2 = pd.Series(fruit_protin,name="Protein")
print(s2)

apple      5.3
banana     1.3
orange     0.9
grapes     2.6
mango      0.8
kiwi       1.1
avacado    2.0
Name: Protein, dtype: float64

In [57]:
# conditional selection
s2[s2>1]
s2[(s2>0.5) & (s2<=2)] #&
s2[~(s2 > 1)]

orange    0.9
mango     0.8
Name: Protein, dtype: float64

In [58]:
#Modifying the values in the series
s2["mango"] = 6.09
s2

apple      5.30
banana     1.30
orange     0.90
grapes     2.60
mango      6.09
kiwi       1.10
avacado    2.00
Name: Protein, dtype: float64

## Data Frame

In [2]:
import numpy as np
#data frame
data = {
    "name": ["Alice", "Bob", "Charlie", "David", "Eve"],
    "age": [25, 30, np.nan, 40, 45],
    "department": ["HR", "IT", "Finance", "Marketing", "Sales"],
    "salary": [50000, 60000, 30000, 80000, 90000,]
}

In [60]:
data

{'name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
 'age': [25, 30, nan, 40, 45],
 'department': ['HR', 'IT', 'Finance', 'Marketing', 'Sales'],
 'salary': [50000, 60000, 30000, 80000, 90000]}

In [3]:
df = pd.DataFrame(data)
df

      name   age department  salary
0    Alice  25.0         HR   50000
1      Bob  30.0         IT   60000
2  Charlie   NaN    Finance   30000
3    David  40.0  Marketing   80000
4      Eve  45.0      Sales   90000

In [62]:
df.head(2)

    name   age department  salary
0  Alice  25.0         HR   50000
1    Bob  30.0         IT   60000

In [63]:
#loc and iloc also works in data frame
df.iloc[1:3]

      name   age department  salary
1      Bob  30.0         IT   60000
2  Charlie   NaN    Finance   30000

In [64]:
df.loc[1:3, ["name", "department"]]

      name department
1      Bob         IT
2  Charlie    Finance
3    David  Marketing

In [65]:
#individual column selection
df["name"]

0      Alice
1        Bob
2    Charlie
3      David
4        Eve
Name: name, dtype: str

In [66]:
#drop a column
df.drop("age", axis=1 ,inplace=True) #use inplace if you want to make changes in original data frame
df

      name department  salary
0    Alice         HR   50000
1      Bob         IT   60000
2  Charlie    Finance   30000
3    David  Marketing   80000
4      Eve      Sales   90000

In [67]:
df.shape

(5, 3)

In [68]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        5 non-null      str
 1   department  5 non-null      str
 2   salary      5 non-null      int64
dtypes: int64(1), str(2)
memory usage: 252.0 bytes

In [69]:
df.describe()

             salary
count      5.000000
mean   62000.000000
std    23874.672773
min    30000.000000
25%    50000.000000
50%    60000.000000
75%    80000.000000
max    90000.000000

In [70]:
# Broad casting
df["salary"] = df["salary"] + 5000
df

      name department  salary
0    Alice         HR   55000
1      Bob         IT   65000
2  Charlie    Finance   35000
3    David  Marketing   85000
4      Eve      Sales   95000

In [71]:
#renaming the column name
df.rename(columns = {'department': 'dept'} , inplace = True)
df

      name       dept  salary
0    Alice         HR   55000
1      Bob         IT   65000
2  Charlie    Finance   35000
3    David  Marketing   85000
4      Eve      Sales   95000

In [72]:
df['dept'].unique()

<StringArray>
['HR', 'IT', 'Finance', 'Marketing', 'Sales']
Length: 5, dtype: str

In [73]:
df["dept"].value_counts()

dept
HR           1
IT           1
Finance      1
Marketing    1
Sales        1
Name: count, dtype: int64

In [74]:
df["promoted_salary"] = df['salary'] * 10
df

      name       dept  salary  promoted_salary
0    Alice         HR   55000           550000
1      Bob         IT   65000           650000
2  Charlie    Finance   35000           350000
3    David  Marketing   85000           850000
4      Eve      Sales   95000           950000

In [75]:
#data cleaning
df.isnull().sum()

name               0
dept               0
salary             0
promoted_salary    0
dtype: int64

In [76]:
# df.dropna()#used to drop any null values from the data frame
# df.dropna(how="all")#used to drop rows where all values are null
# df.dropna(how="any")#used to drop rows where any value is null
df

      name       dept  salary  promoted_salary
0    Alice         HR   55000           550000
1      Bob         IT   65000           650000
2  Charlie    Finance   35000           350000
3    David  Marketing   85000           850000
4      Eve      Sales   95000           950000

In [4]:
df.fillna(df["age"].mean())

      name   age department  salary
0    Alice  25.0         HR   50000
1      Bob  30.0         IT   60000
2  Charlie  35.0    Finance   30000
3    David  40.0  Marketing   80000
4      Eve  45.0      Sales   90000

In [ ]:
df["name"]=df["name"].replace("Alice", "Mukesh")
df

      name   age department  salary
0   Mukesh  25.0         HR   50000
1      Bob  30.0         IT   60000
2  Charlie   NaN    Finance   30000
3    David  40.0  Marketing   80000
4      Eve  45.0      Sales   90000

In [ ]:
df['salary'] = df['salary'].apply(lambda x: x * 2 if x < 100000 else  x)
df

      name   age department    salary
0    Alice  25.0         HR  160000.0
1      Bob  30.0         IT  192000.0
2  Charlie   NaN    Finance  192000.0
3    David  40.0  Marketing  256000.0
4      Eve  45.0      Sales  288000.0

In [ ]:
# name = "alice_fernandez"
# df[["first_name","last_name"]] = df['name'].str.split("_")

In [5]:
# apply and lambda
def multiply_age(x):
    return x * 2
df["age"] = df["age"].apply(multiply_age)
df

      name   age department  salary
0    Alice  50.0         HR   50000
1      Bob  60.0         IT   60000
2  Charlie   NaN    Finance   30000
3    David  80.0  Marketing   80000
4      Eve  90.0      Sales   90000

In [8]:
df["age"] = df["age"].apply(lambda x: x / 2)
df

      name   age department  salary
0    Alice  25.0         HR   50000
1      Bob  30.0         IT   60000
2  Charlie   NaN    Finance   30000
3    David  40.0  Marketing   80000
4      Eve  45.0      Sales   90000

In [17]:
#join and merges
department_info ={
    "department":["HR","IT","FINANCE"],
    "location":["NEW YORK", "SAN FRANCISCO", "CHICAGO"],
    "manager":["Laura", "John", "Emily"]
}
df2 = pd.DataFrame(department_info)
df2

  department       location manager
0         HR       NEW YORK   Laura
1         IT  SAN FRANCISCO    John
2    FINANCE        CHICAGO   Emily

In [19]:
#Concat
df_concat = pd.concat([df, df2])
df_concat

      name   age department   salary       location manager
0    Alice  25.0         HR  50000.0            NaN     NaN
1      Bob  30.0         IT  60000.0            NaN     NaN
2  Charlie   NaN    Finance  30000.0            NaN     NaN
3    David  40.0  Marketing  80000.0            NaN     NaN
4      Eve  45.0      Sales  90000.0            NaN     NaN
0      NaN   NaN         HR      NaN       NEW YORK   Laura
1      NaN   NaN         IT      NaN  SAN FRANCISCO    John
2      NaN   NaN    FINANCE      NaN        CHICAGO   Emily

In [20]:
pd.concat([df, df2], axis=1)

      name   age department  salary department       location manager
0    Alice  25.0         HR   50000         HR       NEW YORK   Laura
1      Bob  30.0         IT   60000         IT  SAN FRANCISCO    John
2  Charlie   NaN    Finance   30000    FINANCE        CHICAGO   Emily
3    David  40.0  Marketing   80000        NaN            NaN     NaN
4      Eve  45.0      Sales   90000        NaN            NaN     NaN

In [21]:
pd.merge(df,df2,on="department")

    name   age department  salary       location manager
0  Alice  25.0         HR   50000       NEW YORK   Laura
1    Bob  30.0         IT   60000  SAN FRANCISCO    John

In [24]:
#operations on file
data = pd.read_csv("sales.csv")
data.head()

,P_ID,P_Name,Category,Qty_Sold,Unit_Price,Total_Sales,Order_Date,Region,Ship_Mode,Customer_Segment,Profit
0,P101,Laptop,Electronics,5,55000,275000,10/01/2026,West,Standard Class,Consumer,35000
1,P102,Smartphone,Electronics,8,20000,160000,12/01/2026,East,Second Class,Corporate,22000
2,P103,Office Chair,Furniture,10,4500,45000,14/01/2026,South,Standard Class,Home Office,7000
3,P104,Printer,Electronics,3,12000,36000,16/01/2026,North,First Class,Consumer,5000
4,P105,Study Table,Furniture,4,7000,28000,18/01/2026,West,Same Day,Corporate,4000

In [25]:
data.shape

(10, 11)

In [26]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   P_ID              10 non-null     str
 1   P_Name            10 non-null     str
 2   Category          10 non-null     str
 3   Qty_Sold          10 non-null     int64
 4   Unit_Price        10 non-null     int64
 5   Total_Sales       10 non-null     int64
 6   Order_Date        10 non-null     str
 7   Region            10 non-null     str
 8   Ship_Mode         10 non-null     str
 9   Customer_Segment  10 non-null     str
 10  Profit            10 non-null     int64
dtypes: int64(4), str(7)
memory usage: 1012.0 bytes