## Pandas

In [114]:
import pandas as pd

In [12]:
s = pd.Series([10,20,30,40,50,60])
s.name = "Calories"
print(s)

0    10
1    20
2    30
3    40
4    50
5    60
Name: Numbers, dtype: int64

In [9]:
s.dtype
s.values

array([10, 20, 30, 40, 50, 60])

In [13]:
s.index

RangeIndex(start=0, stop=6, step=1)

In [17]:
s[0:3]

0    10
1    20
2    30
Name: Numbers, dtype: int64

In [19]:
#iloc -> location based indexing
s.iloc[3]

np.int64(40)

In [21]:
s.iloc[0:3]

0    10
1    20
2    30
Name: Numbers, dtype: int64

In [27]:
index = ["apple", "banana", "orange", "grapes", "mango", "kiwi"]
s.index = index
print(s)
print(s["grapes"])

apple     10
banana    20
orange    30
grapes    40
mango     50
kiwi      60
Name: Numbers, dtype: int64
40

In [32]:
#loc -> label based indexing
print(s.loc[["grapes", "mango"]])
#In the label based indexing your start as well as end index is included in the output.
s.loc["banana":"grapes"]

grapes    40
mango     50
Name: Numbers, dtype: int64

banana    20
orange    30
grapes    40
Name: Numbers, dtype: int64

In [37]:
fruit_protin = {
    "apple": 5.3,
    "banana": 1.3,
    "orange": 0.9,
    "grapes": 2.6,
    "mango": 0.8,
    "kiwi": 1.1,
    "avacado": 2.0
}
s2 = pd.Series(fruit_protin,name="Protein")
print(s2)

apple      5.3
banana     1.3
orange     0.9
grapes     2.6
mango      0.8
kiwi       1.1
avacado    2.0
Name: Protein, dtype: float64

In [45]:
# conditional selection
s2[s2>1]
s2[(s2>0.5) & (s2<=2)] #&
s2[~(s2 > 1)]

orange    0.9
mango     0.8
Name: Protein, dtype: float64

In [48]:
#Modifying the values in the series
s2["mango"] = 6.09
s2

apple      5.30
banana     1.30
orange     0.90
grapes     2.60
mango      6.09
kiwi       1.10
avacado    2.00
Name: Protein, dtype: float64

## Data Frame

In [108]:
import numpy as np
#data frame
data = {
    "name": ["Alice", "Bob", "Charlie", "David", "Eve"],
    "age": [25, 30, np.nan, 40, 45],
    "department": ["HR", "IT", "Finance", "Marketing", "Sales"],
    "salary": [50000, 60000, 30000, 80000, 90000,]
}

In [54]:
data

{'name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
 'age': [25, 30, 35, 40, 45],
 'department': ['HR', 'IT', 'Finance', 'Marketing', 'Sales'],
 'salary': [50000, 60000, 70000, nan, 80000, 90000]}

In [110]:
df = pd.DataFrame(data)
df

      name   age department  salary
0    Alice  25.0         HR   50000
1      Bob  30.0         IT   60000
2  Charlie   NaN    Finance   30000
3    David  40.0  Marketing   80000
4      Eve  45.0      Sales   90000

In [65]:
df.head(2)

    name  age department   salary
0  Alice   25         HR  50000.0
1    Bob   30         IT  60000.0

In [67]:
#loc and iloc also works in data frame
df.iloc[1:3]

      name  age department   salary
1      Bob   30         IT  60000.0
2  Charlie   35    Finance      NaN

In [69]:
df.loc[1:3, ["name", "department"]]

      name department
1      Bob         IT
2  Charlie    Finance
3    David  Marketing

In [71]:
#individual column selection
df["name"]

0      Alice
1        Bob
2    Charlie
3      David
4        Eve
Name: name, dtype: str

In [ ]:
#drop a column
df.drop("age", axis=1 ,inplace=True) #use inplace if you want to make changes in original data frame
df

      name department  salary
0    Alice         HR   50000
1      Bob         IT   60000
2  Charlie    Finance   30000
3    David  Marketing   80000
4      Eve      Sales   90000

In [89]:
df.shape

(5, 3)

In [91]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        5 non-null      str
 1   department  5 non-null      str
 2   salary      5 non-null      int64
dtypes: int64(1), str(2)
memory usage: 252.0 bytes

In [93]:
df.describe()

             salary
count      5.000000
mean   62000.000000
std    23874.672773
min    30000.000000
25%    50000.000000
50%    60000.000000
75%    80000.000000
max    90000.000000

In [95]:
# Broad casting
df["salary"] = df["salary"] + 5000
df

      name department  salary
0    Alice         HR   60000
1      Bob         IT   70000
2  Charlie    Finance   40000
3    David  Marketing   90000
4      Eve      Sales  100000

In [97]:
#renaming the column name
df.rename(columns = {'department': 'dept'} , inplace = True)
df

      name       dept  salary
0    Alice         HR   60000
1      Bob         IT   70000
2  Charlie    Finance   40000
3    David  Marketing   90000
4      Eve      Sales  100000

In [100]:
df['dept'].unique()

<StringArray>
['HR', 'IT', 'Finance', 'Marketing', 'Sales']
Length: 5, dtype: str

In [102]:
df["dept"].value_counts()

dept
HR           1
IT           1
Finance      1
Marketing    1
Sales        1
Name: count, dtype: int64

In [104]:
df["promoted_salary"] = df['salary'] * 10
df

      name       dept  salary  promoted_salary
0    Alice         HR   60000           600000
1      Bob         IT   70000           700000
2  Charlie    Finance   40000           400000
3    David  Marketing   90000           900000
4      Eve      Sales  100000          1000000

In [106]:
#data cleaning
df.isnull().sum()

name               0
dept               0
salary             0
promoted_salary    0
dtype: int64

In [112]:
# df.dropna()#used to drop any null values from the data frame
# df.dropna(how="all")#used to drop rows where all values are null
# df.dropna(how="any")#used to drop rows where any value is null
df

      name   age department  salary
0    Alice  25.0         HR   50000
1      Bob  30.0         IT   60000
2  Charlie   NaN    Finance   30000
3    David  40.0  Marketing   80000
4      Eve  45.0      Sales   90000

In [125]:
df.fillna(df["age"].mean())

      name   age department  salary
0    Alice  25.0         HR   50000
1      Bob  30.0         IT   60000
2  Charlie  35.0    Finance   30000
3    David  40.0  Marketing   80000
4      Eve  45.0      Sales   90000

In [128]:
df["name"]=df["name"].replace("Alice", "Kamlesh")
df

      name   age department  salary
0  Kamlesh  25.0         HR   50000
1      Bob  30.0         IT   60000
2  Charlie   NaN    Finance   30000
3    David  40.0  Marketing   80000
4      Eve  45.0      Sales   90000